flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/name: llano_music
description: Aplicación de música llanera
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

flutter:
  assets:
    - assets/audio/
    - assets/images/
