name: llano_music_app
description: La aplicación del auténtico sonido del Llano

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Audios
    - assets/audio/roberto_carballo/
    - assets/audio/edwin_trosel/
    - assets/audio/francisco_camacho/
    - assets/audio/omar_garcia/
    - assets/audio/nicolas_castillo/
    - assets/audio/enrique_de_la_vega/
    - assets/audio/jose_angel_cordero/
    - assets/audio/mary_pacheco/
    - assets/audio/manuel_oliveros/
    - assets/audio/fabiana_diaz/
    - assets/audio/tatiana_lopez/
    - assets/audio/clasicos/

    # Banners
    - assets/banners/

    # Imágenes
    - assets/images/artistas/
    - assets/images/clasicos/
    - assets/images/logo/
    - assets/images/icons/
